
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productApp
    username: root
    password: pvi@2021
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: PRODUCT-SERVICE